### ISSUE TITLE
ReactiveUserRepository.withDelay has an error, resulting in error on build

### ISSUE THREAD

**Issue by Thisen** [eddumelendez/reactor-kotlin-workshop#2]
This function in ReactiveUserRepository has an error and therefore the project can't build:

`
fun withDelay(userMono: Mono<User>) : Mono<User> {
return Mono.delay(Duration.ofMillis(delayInMs)).then(Supplier { userMono })
}
`

**The error:**
Type inference failed. Expected type mismatch: 
required: Mono<User!>!
found: Supplier<Mono<User>>

**Comment by eddumelendez** [comment]
Thanks for the report. It's already fixed in master branch
