### ISSUE TITLE
Part08OtherOperations, nullHandling

### ISSUE THREAD

**Issue by aljacinto** [eddumelendez/reactor-kotlin-workshop#3]
This one doesn't pass because like you mentioned on your hint, reactive doesn't take null values.  Just making sure I don't miss anything or I'm doing something wrong.

Great job converting the workshop to kotlin, learned a lot.  Thanks!

**Comment by eddumelendez** [comment]
Hi @aljacinto this is solved by #4 . Thanks for reporting this issue and sorry for the delay
